global:
  scrape_interval: 5s
  external_labels:
    monitor: 'suresh-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['server_ip:9090'] ## IP Address of the local host

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['server_ip:9100']

  - job_name: 'cAdvisor'
    static_configs:
      - targets: ['server_ip:8080']